### ISSUE TITLE
birdseye IS 3.8 compatible, apparently

### ISSUE THREAD

**Issue by nicois** [alexmojaki/snoop#17]
I see the following, running under Python 3.8:

```python
Traceback (most recent call last):
  File "route.py", line 73, in <module>
    def handle_change(change: ChangeType) -> None:
  File "/usr/local/lib/python3.8/site-packages/snoop/tracer.py", line 290, in __call__
    raise Exception("birdseye doesn't support this version of Python")
Exception: birdseye doesn't support this version of Python
```

Going by <a href="https://github.com/alexmojaki/birdseye/issues/80">this</a>, that isn't the case. Can the exception be removed?

**Comment by alexmojaki** [comment]
Thanks, this has been fixed now in #18 and released, you can upgrade.
